// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB-XOOxswkZshwdBr0oWdCSDBowk5hI7M',
    appId: '1:975023238419:web:cdf8e426f97722534abee6',
    messagingSenderId: '975023238419',
    projectId: 'medtrack-7335b',
    authDomain: 'medtrack-7335b.firebaseapp.com',
    storageBucket: 'medtrack-7335b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqjQtdoa8Jcab5h_68WG5mQw_Mvy6QG8k',
    appId: '1:975023238419:android:2335afb35c5f99cd4abee6',
    messagingSenderId: '975023238419',
    projectId: 'medtrack-7335b',
    storageBucket: 'medtrack-7335b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_e8qogSdDPU2aqsuhQUZ3-Dwti9wY99w',
    appId: '1:975023238419:ios:32184a58ed20c8454abee6',
    messagingSenderId: '975023238419',
    projectId: 'medtrack-7335b',
    storageBucket: 'medtrack-7335b.firebasestorage.app',
    iosBundleId: 'com.example.uhd',
  );
}
